In [1]:
import sys
import time
sys.path.insert(0, '/home/anish/ASC_ML')

In [2]:
import pandas as pd
import dask.dataframe as dd

In [3]:
from ASC_ML.preprocessing import dataset_container as dc
from ASC_ML.preprocessing import data_cleaning as data_cl

In [4]:
df = dd.read_csv("/home/anish/Downloads/autokeras-regression-master/Data.csv")

In [5]:
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [6]:
target_col = "sales"
X = df.loc[:, df.columns != target_col]
y = df.loc[:, target_col]

In [7]:
data_cl_obj = data_cl.DataCleaning(["sales"], df)

In [8]:
data_cl_obj.col_info

{'TV': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 190},
 'radio': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 167},
 'newspaper': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 172},
 'sales': {'dtype': dtype('float64'),
  'is_label': True,
  'missing': 0.0,
  'cardinality': 121}}

In [9]:
data_cl_obj.dataset.get()[0].compute()

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [10]:
data_cl_obj.dataset.get()[0]["sales"].compute()

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ...
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [11]:
directory_train = "/home/anish/ASC-ML-EXP-DATASETS/LinReg-tabular/house-prices-advanced-regression-techniques/train.csv"
directory_test = "/home/anish/ASC-ML-EXP-DATASETS/LinReg-tabular/house-prices-advanced-regression-techniques/test.csv"
train_df = dd.read_csv(directory_train, assume_missing = True, sample_rows=1000)
test_df = dd.read_csv(directory_test, assume_missing = True, sample_rows=1000)

In [12]:
train_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1.0,60.0,RL,65.0,8450.0,Pave,NaN,Reg,Lvl,AllPub,...,0.0,NaN,NaN,NaN,0.0,2.0,2008.0,WD,Normal,208500.0
1,2.0,20.0,RL,80.0,9600.0,Pave,NaN,Reg,Lvl,AllPub,...,0.0,NaN,NaN,NaN,0.0,5.0,2007.0,WD,Normal,181500.0
2,3.0,60.0,RL,68.0,11250.0,Pave,NaN,IR1,Lvl,AllPub,...,0.0,NaN,NaN,NaN,0.0,9.0,2008.0,WD,Normal,223500.0
3,4.0,70.0,RL,60.0,9550.0,Pave,NaN,IR1,Lvl,AllPub,...,0.0,NaN,NaN,NaN,0.0,2.0,2006.0,WD,Abnorml,140000.0
4,5.0,60.0,RL,84.0,14260.0,Pave,NaN,IR1,Lvl,AllPub,...,0.0,NaN,NaN,NaN,0.0,12.0,2008.0,WD,Normal,250000.0

In [13]:
data_cl_obj = data_cl.DataCleaning(["SalePrice"], train_dataframe = train_df, test_dataframe = test_df)

In [14]:
data_cl_obj.col_info

{'Id': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 1460},
 'MSSubClass': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 15},
 'MSZoning': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 5},
 'LotFrontage': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.1773972602739726,
  'cardinality': 110},
 'LotArea': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 1073},
 'Street': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 2},
 'Alley': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.9376712328767123,
  'cardinality': 2},
 'LotShape': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 4},
 'LandContour': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 4},
 'Utilities': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 2},
 'LotConfig': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 5},
 'LandSlope': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 3},
 'Neighborhood': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 25},
 'Condition1': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 9},
 'Condition2': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 8},
 'BldgType': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 5},
 'HouseStyle': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 8},
 'OverallQual': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 10},
 'OverallCond': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 9},
 'YearBuilt': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 112},
 'YearRemodAdd': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 61},
 'RoofStyle': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 6},
 'RoofMatl': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 8},
 'Exterior1st': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 15},
 'Exterior2nd': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 16},
 'MasVnrType': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.005479452054794521,
  'cardinality': 4},
 'MasVnrArea': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.005479452054794521,
  'cardinality': 327},
 'ExterQual': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 4},
 'ExterCond': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 5},
 'Foundation': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 6},
 'BsmtQual': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.025342465753424658,
  'cardinality': 4},
 'BsmtCond': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.025342465753424658,
  'cardinality': 4},
 'BsmtExposure': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.026027397260273973,
  'cardinality': 4},
 'BsmtFinType1': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.025342465753424658,
  'cardinality': 6},
 'BsmtFinSF1': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 637},
 'BsmtFinType2': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.026027397260273973,
  'cardinality': 6},
 'BsmtFinSF2': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 144},
 'BsmtUnfSF': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 780},
 'TotalBsmtSF': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 721},
 'Heating': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 6},
 'HeatingQC': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 5},
 'CentralAir': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 2},
 'Electrical': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0006849315068493151,
  'cardinality': 5},
 '1stFlrSF': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 753},
 '2ndFlrSF': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 417},
 'LowQualFinSF': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 24},
 'GrLivArea': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 861},
 'BsmtFullBath': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 4},
 'BsmtHalfBath': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 3},
 'FullBath': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 4},
 'HalfBath': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 3},
 'BedroomAbvGr': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 8},
 'KitchenAbvGr': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 4},
 'KitchenQual': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 4},
 'TotRmsAbvGrd': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 12},
 'Functional': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 7},
 'Fireplaces': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 4},
 'FireplaceQu': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.4726027397260274,
  'cardinality': 5},
 'GarageType': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.05547945205479452,
  'cardinality': 6},
 'GarageYrBlt': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.05547945205479452,
  'cardinality': 97},
 'GarageFinish': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.05547945205479452,
  'cardinality': 3},
 'GarageCars': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 5},
 'GarageArea': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 441},
 'GarageQual': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.05547945205479452,
  'cardinality': 5},
 'GarageCond': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.05547945205479452,
  'cardinality': 5},
 'PavedDrive': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 3},
 'WoodDeckSF': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 274},
 'OpenPorchSF': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 202},
 'EnclosedPorch': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 120},
 '3SsnPorch': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 20},
 'ScreenPorch': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 76},
 'PoolArea': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 8},
 'PoolQC': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.9952054794520548,
  'cardinality': 3},
 'Fence': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.8075342465753425,
  'cardinality': 4},
 'MiscFeature': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.963013698630137,
  'cardinality': 4},
 'MiscVal': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 21},
 'MoSold': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 12},
 'YrSold': {'dtype': dtype('float64'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 5},
 'SaleType': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 9},
 'SaleCondition': {'dtype': dtype('O'),
  'is_label': False,
  'missing': 0.0,
  'cardinality': 6},
 'SalePrice': {'dtype': dtype('float64'),
  'is_label': True,
  'missing': 0.0,
  'cardinality': 663}}

In [15]:
data_cl_obj.encode()

In [16]:
data_cl_obj.dataset.get()[0].compute()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1.0,60.0,0,65.0,8450.0,0,0,0,0,0,...,0.0,0,0,0,0.0,2.0,2008.0,0,0,208500.0
1,2.0,20.0,0,80.0,9600.0,0,0,0,0,0,...,0.0,0,0,0,0.0,5.0,2007.0,0,0,181500.0
2,3.0,60.0,0,68.0,11250.0,0,0,1,0,0,...,0.0,0,0,0,0.0,9.0,2008.0,0,0,223500.0
3,4.0,70.0,0,60.0,9550.0,0,0,1,0,0,...,0.0,0,0,0,0.0,2.0,2006.0,0,1,140000.0
4,5.0,60.0,0,84.0,14260.0,0,0,1,0,0,...,0.0,0,0,0,0.0,12.0,2008.0,0,0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456.0,60.0,0,62.0,7917.0,0,0,0,0,0,...,0.0,0,0,0,0.0,8.0,2007.0,0,0,175000.0
1456,1457.0,20.0,0,85.0,13175.0,0,0,0,0,0,...,0.0,0,1,0,0.0,2.0,2010.0,0,0,210000.0
1457,1458.0,70.0,0,66.0,9042.0,0,0,0,0,0,...,0.0,0,3,1,2500.0,5.0,2010.0,0,0,266500.0
1458,1459.0,20.0,0,68.0,9717.0,0,0,0,0,0,...,0.0,0,0,0,0.0,4.0,2010.0,0,0,142125.0
1459,1460.0,20.0,0,75.0,9937.0,0,0,0,0,0,...,0.0,0,0,0,0.0,6.0,2008.0,0,0,147500.0

In [17]:
data_cl_obj.dataset.get(types = ["train"])[0].compute()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1.0,60.0,0,65.0,8450.0,0,0,0,0,0,...,0.0,0,0,0,0.0,2.0,2008.0,0,0,208500.0
1,2.0,20.0,0,80.0,9600.0,0,0,0,0,0,...,0.0,0,0,0,0.0,5.0,2007.0,0,0,181500.0
2,3.0,60.0,0,68.0,11250.0,0,0,1,0,0,...,0.0,0,0,0,0.0,9.0,2008.0,0,0,223500.0
3,4.0,70.0,0,60.0,9550.0,0,0,1,0,0,...,0.0,0,0,0,0.0,2.0,2006.0,0,1,140000.0
4,5.0,60.0,0,84.0,14260.0,0,0,1,0,0,...,0.0,0,0,0,0.0,12.0,2008.0,0,0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456.0,60.0,0,62.0,7917.0,0,0,0,0,0,...,0.0,0,0,0,0.0,8.0,2007.0,0,0,175000.0
1456,1457.0,20.0,0,85.0,13175.0,0,0,0,0,0,...,0.0,0,1,0,0.0,2.0,2010.0,0,0,210000.0
1457,1458.0,70.0,0,66.0,9042.0,0,0,0,0,0,...,0.0,0,3,1,2500.0,5.0,2010.0,0,0,266500.0
1458,1459.0,20.0,0,68.0,9717.0,0,0,0,0,0,...,0.0,0,0,0,0.0,4.0,2010.0,0,0,142125.0
1459,1460.0,20.0,0,75.0,9937.0,0,0,0,0,0,...,0.0,0,0,0,0.0,6.0,2008.0,0,0,147500.0

In [18]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

In [27]:
X = data_cl_obj.dataset.get(types = ["train"])[0].compute()
Y = data_cl_obj.dataset.get(types = ["train"])[0]["SalePrice"].compute()
model = RandomForestClassifier()
n = 10
rfe = RFE(estimator = model, n_features_to_select=n)
fit = rfe.fit(X, Y)
X = X[X.columns[fit.support_]]
X.head()

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').