In [98]:
import os
# import pandas as pd
import dask.dataframe as dd
import functools
import time

In [54]:
#User input(could be either folder name or direct csv file path)
directory_path = "/home/anish/ASC-ML-EXP-DATASETS/LinReg-tabular/house-prices-advanced-regression-techniques/"

#Expected csv file name (give option of already train test split)
train_file = "train.csv"
train_dir = os.path.join(directory_path, train_file)
print(train_dir)

/home/anish/ASC-ML-EXP-DATASETS/LinReg-tabular/house-prices-advanced-regression-techniques/train.csv

In [55]:
dataset = dd.read_csv(train_dir, sample_rows=2000)
# Get no. of rows = dataset.shape[0].compute()
# dataset_pd = pd.read_csv(train_dir)
# datatypes = dataset_pd.dtypes.to_dict()
# dataset = dd.read_csv(train_dir, dtype = datatypes)

In [56]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [85]:
#Takes path of directory and finds train.csv, test.csv or direct path of singular .csv file
class Dataframe_extractor_csv:
    def __init__(self, directory_path):
        self._directory_path = directory_path
        
    @property
    def directory_path(self):
        return self._directory_path
    
    #returns list of dask dataframe [singular_df] or [train_df,test_df]
    def return_dask_df(self):
        df_list = []
        
        #If csv file path has been entered
        if self._directory_path.endswith(".csv"):
            print("Reading single csv file path")
            df_list.append(dd.read_csv(self._directory_path, assume_missing = True, sample_rows=1000))
            
        #Finding train.csv and test.csv from directory
        else:
            print("Reading train.csv and test.csv of directory")
            train_dir = os.path.join(self._directory_path, "train.csv")
            self._check_dir_exists(train_dir)
            
            test_dir = os.path.join(self._directory_path, "test.csv")
            self._check_dir_exists(test_dir)
    
            #train_df = dd.read_csv(train_dir)
            #test_df = dd.read_csv(test_dir)
            df_list.append(dd.read_csv(train_dir, assume_missing = True, sample_rows=1000))
            df_list.append(dd.read_csv(test_dir, assume_missing = True, sample_rows=1000))
        
        #If no datasets are found
        if not df_list:
            raise EmptyListError("No Datasets found")
            
        return df_list
        
    @staticmethod
    def _check_dir_exists(directory):
        if(not os.path.isfile(directory)):
            raise FileNotFoundError(f"Directory {directory} does not exist")

In [86]:
data_item = Dataframe_extractor_csv(directory_path)

In [87]:
print("train_dataset")
data_item.return_dask_df()[0].head()

train_dataset
Reading train.csv and test.csv of directory

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1.0,60.0,RL,65.0,8450.0,Pave,NaN,Reg,Lvl,AllPub,...,0.0,NaN,NaN,NaN,0.0,2.0,2008.0,WD,Normal,208500.0
1,2.0,20.0,RL,80.0,9600.0,Pave,NaN,Reg,Lvl,AllPub,...,0.0,NaN,NaN,NaN,0.0,5.0,2007.0,WD,Normal,181500.0
2,3.0,60.0,RL,68.0,11250.0,Pave,NaN,IR1,Lvl,AllPub,...,0.0,NaN,NaN,NaN,0.0,9.0,2008.0,WD,Normal,223500.0
3,4.0,70.0,RL,60.0,9550.0,Pave,NaN,IR1,Lvl,AllPub,...,0.0,NaN,NaN,NaN,0.0,2.0,2006.0,WD,Abnorml,140000.0
4,5.0,60.0,RL,84.0,14260.0,Pave,NaN,IR1,Lvl,AllPub,...,0.0,NaN,NaN,NaN,0.0,12.0,2008.0,WD,Normal,250000.0

In [88]:
print("test_dataset")
data_item.return_dask_df()[1].head()

test_dataset
Reading train.csv and test.csv of directory

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461.0,20.0,RH,80.0,11622.0,Pave,NaN,Reg,Lvl,AllPub,...,120.0,0.0,NaN,MnPrv,NaN,0.0,6.0,2010.0,WD,Normal
1,1462.0,20.0,RL,81.0,14267.0,Pave,NaN,IR1,Lvl,AllPub,...,0.0,0.0,NaN,NaN,Gar2,12500.0,6.0,2010.0,WD,Normal
2,1463.0,60.0,RL,74.0,13830.0,Pave,NaN,IR1,Lvl,AllPub,...,0.0,0.0,NaN,MnPrv,NaN,0.0,3.0,2010.0,WD,Normal
3,1464.0,60.0,RL,78.0,9978.0,Pave,NaN,IR1,Lvl,AllPub,...,0.0,0.0,NaN,NaN,NaN,0.0,6.0,2010.0,WD,Normal
4,1465.0,120.0,RL,43.0,5005.0,Pave,NaN,IR1,HLS,AllPub,...,144.0,0.0,NaN,NaN,NaN,0.0,1.0,2010.0,WD,Normal

In [96]:
timeit.timeit('data_item.return_dask_df()', globals=globals(), number=1)

Reading train.csv and test.csv of directory

0.06733309899937012

In [100]:
start_time = time.time()
data_item = Dataframe_extractor_csv(directory_path)
data_item.return_dask_df()[0]
data_item.return_dask_df()[1]
print("--- %s seconds ---" % (time.time() - start_time))

Reading train.csv and test.csv of directory
Reading train.csv and test.csv of directory
--- 0.10629582405090332 seconds ---

In [101]:
#Takes path of directory and finds train.csv, test.csv or direct path of singular .csv file
class Dataframe_extractor_csv:
    def __init__(self, directory_path):
        self._directory_path = directory_path
        
    @property
    def directory_path(self):
        return self._directory_path
    
    #returns list of dask dataframe [singular_df] or [train_df,test_df]
    @functools.lru_cache(maxsize=128)
    def return_dask_df(self):
        df_list = []
        
        #If csv file path has been entered
        if self._directory_path.endswith(".csv"):
            print("Reading single csv file path")
            df_list.append(dd.read_csv(self._directory_path, assume_missing = True, sample_rows=1000))
            
        #Finding train.csv and test.csv from directory
        else:
            print("Reading train.csv and test.csv of directory")
            train_dir = os.path.join(self._directory_path, "train.csv")
            self._check_dir_exists(train_dir)
            
            test_dir = os.path.join(self._directory_path, "test.csv")
            self._check_dir_exists(test_dir)
    
            #train_df = dd.read_csv(train_dir)
            #test_df = dd.read_csv(test_dir)
            df_list.append(dd.read_csv(train_dir, assume_missing = True, sample_rows=1000))
            df_list.append(dd.read_csv(test_dir, assume_missing = True, sample_rows=1000))
        
        #If no datasets are found
        if not df_list:
            raise EmptyListError("No Datasets found")
            
        return df_list
        
    @staticmethod
    def _check_dir_exists(directory):
        if(not os.path.isfile(directory)):
            raise FileNotFoundError(f"Directory {directory} does not exist")

In [108]:
start_time = time.time()
data_item = Dataframe_extractor_csv(directory_path)
data_item.return_dask_df()[0]
data_item.return_dask_df()[1]
print("--- %s seconds ---" % (time.time() - start_time))

Reading train.csv and test.csv of directory
--- 0.0694122314453125 seconds ---

In [106]:
data_item.return_dask_df()[0].head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1.0,60.0,RL,65.0,8450.0,Pave,NaN,Reg,Lvl,AllPub,...,0.0,NaN,NaN,NaN,0.0,2.0,2008.0,WD,Normal,208500.0
1,2.0,20.0,RL,80.0,9600.0,Pave,NaN,Reg,Lvl,AllPub,...,0.0,NaN,NaN,NaN,0.0,5.0,2007.0,WD,Normal,181500.0
2,3.0,60.0,RL,68.0,11250.0,Pave,NaN,IR1,Lvl,AllPub,...,0.0,NaN,NaN,NaN,0.0,9.0,2008.0,WD,Normal,223500.0
3,4.0,70.0,RL,60.0,9550.0,Pave,NaN,IR1,Lvl,AllPub,...,0.0,NaN,NaN,NaN,0.0,2.0,2006.0,WD,Abnorml,140000.0
4,5.0,60.0,RL,84.0,14260.0,Pave,NaN,IR1,Lvl,AllPub,...,0.0,NaN,NaN,NaN,0.0,12.0,2008.0,WD,Normal,250000.0

In [104]:
data_item.return_dask_df()[1]

Dask DataFrame Structure:
                    Id MSSubClass MSZoning LotFrontage  LotArea  Street   Alley LotShape LandContour Utilities LotConfig LandSlope Neighborhood Condition1 Condition2 BldgType HouseStyle OverallQual OverallCond YearBuilt YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure BsmtFinType1 BsmtFinSF1 BsmtFinType2 BsmtFinSF2 BsmtUnfSF TotalBsmtSF Heating HeatingQC CentralAir Electrical 1stFlrSF 2ndFlrSF LowQualFinSF GrLivArea BsmtFullBath BsmtHalfBath FullBath HalfBath BedroomAbvGr KitchenAbvGr KitchenQual TotRmsAbvGrd Functional Fireplaces FireplaceQu GarageType GarageYrBlt GarageFinish GarageCars GarageArea GarageQual GarageCond PavedDrive WoodDeckSF OpenPorchSF EnclosedPorch 3SsnPorch ScreenPorch PoolArea  PoolQC   Fence MiscFeature  MiscVal   MoSold   YrSold SaleType SaleCondition
npartitions=1
               float64    float64   object     float64  float64  object  object   object      object    object    object    object       object     object     object   object     object     float64     float64   float64      float64    object   object      object      object     object    float64    object    object     object   object   object       object       object    float64       object    float64   float64     float64  object    object     object     object  float64  float64      float64   float64      float64      float64  float64  float64      float64      float64      object      float64     object    float64      object     object     float64       object    float64    float64     object     object     object    float64     float64       float64   float64     float64  float64  object  object      object  float64  float64  float64   object        object
                   ...        ...      ...         ...      ...     ...     ...      ...         ...       ...       ...       ...          ...        ...        ...      ...        ...         ...         ...       ...          ...       ...      ...         ...         ...        ...        ...       ...       ...        ...      ...      ...          ...          ...        ...          ...        ...       ...         ...     ...       ...        ...        ...      ...      ...          ...       ...          ...          ...      ...      ...          ...          ...         ...          ...        ...        ...         ...        ...         ...          ...        ...        ...        ...        ...        ...        ...         ...           ...       ...         ...      ...     ...     ...         ...      ...      ...      ...      ...           ...
Dask Name: read-csv, 1 tasks

In [75]:
directory = "/home/anish/ASC-ML-EXP-DATASETS/LinReg-tabular/weather-history-dataset/weatherHistory.csv"

In [84]:
data_item2 = Dataframe_extractor_csv(directory)
print("Dataset")
data_item2.return_dask_df()[0].head()

Dataset
Reading single csv file path

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.